---

dnsName: spongo.ru
dnsIp: 91.149.218.39

nebula:
  localIp: 192.168.49.1
  dir: /etc/nebula
  url: https://github.com/slackhq/nebula/releases/download/v1.9.5/nebula-linux-amd64.tar.gz
  caName: SPONGO INC
  duration: 175200h
  clients:
    lighthouse:
      ip: 192.168.49.1/24
    router:
      ip: 192.168.49.2/24
    mac:
      ip: 192.168.49.3/24
    iphone:
      ip: 192.168.49.4/24
