---

dnsName: spongo.ru
dnsIp: 91.149.218.39

haproxy:
  - name: www
    ip: 192.168.49.2
    port: 8888
    proxy: false
  - name: vpn
    ip: 127.0.0.1
    port: 9443
    proxy: false
  - name: nebula
    ip: 127.0.0.1
    port: 4242
    proxy: false
  - name: shadowsocks
    ip: 127.0.0.1
    port: 9389
    proxy: false
  - name: argo
    ip: 12.12.12.0
    port: 443
    proxy: false
  - name: gitea
    ip: 12.12.12.1
    port: 443
    proxy: false
  - name: vault
    ip: 12.12.12.1
    port: 443
    proxy: false
  - name: nexus
    ip: 12.12.12.1
    port: 443
    proxy: false
  - name: webdaw
    ip: 192.168.49.2
    port: 8088
    proxy: false
  - name: player
    ip: 192.168.49.2
    port: 8000
    proxy: false
  - name: switch
    ip: 192.168.49.2
    port: 8886
    proxy: false
  - name: switch2
    ip: 192.168.49.2
    port: 8887
    proxy: false
