name: loadbalancer-shadowsocks
on:
  push:
    branches: [ "main" ]
    paths:
      - ansible/loadbalancer-shadowsocks/**

  workflow_dispatch:
jobs:
  provision:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v3
        with:
          playbook: shadowsocks.yaml
          directory: ansible/loadbalancer-shadowsocks/
          key: ${{ secrets.PRIVATE }}
          options: |
            --inventory hosts.yaml
            --extra-vars sspassword=${{ secrets.SSPASS }}