name: loadbalancer-haproxy
on:
  push:
    branches: [ "main" ]
    paths:
      - ansible/loadbalancer-haproxy/**

  workflow_dispatch:
jobs:
  provision:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v3
        with:
          playbook: haproxy.yaml
          directory: ansible/loadbalancer-haproxy/
          key: ${{ secrets.PRIVATE }}
          options: |
            --inventory hosts.yaml